version: 2
updates:
  # Enable version updates for npm (build tools)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "CanerKaraca23"
    assignees:
      - "CanerKaraca23"
    commit-message:
      prefix: "npm"
      include: "scope"
    
  # Enable version updates for bundler (Jekyll and gems)
  - package-ecosystem: "bundler" 
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "CanerKaraca23"
    assignees:
      - "CanerKaraca23"
    commit-message:
      prefix: "bundle"
      include: "scope"
      
  # Enable version updates for GitHub Actions (if any workflows are added)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
