version: 2
updates:
  # GitHub Actions workflow dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  # npm dependencies for Node.js/Gulp build tools
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  # Bundler/Ruby dependencies for Jekyll
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
